name: "Lingo.Dev AI Localization"
description: Automated AI localization for dev teams.
author: Lingo.dev

branding:
  icon: "aperture"
  color: "black"

runs:
  using: "composite"
  steps:
    - name: Run
      run: |
        npx @whisperlab/lingo.dev@latest ci \
          --api-key "${{ inputs.api-key }}" \
          --pull-request "${{ inputs.pull-request }}" \
          --commit-message "${{ inputs.commit-message }}" \
          --pull-request-title "${{ inputs.pull-request-title }}" \
          --working-directory "${{ inputs.working-directory }}" \
          --process-own-commits "${{ inputs.process-own-commits }}"
      shell: bash
inputs:
  api-key:
    description: "Lingo.dev Platform API Key"
    required: true
  pull-request:
    description: "Create a pull request with the changes"
    default: false
    required: false
  commit-message:
    description: "Commit message"
    default: "feat: update translations via @LingoDotDev"
    required: false
  pull-request-title:
    description: "Pull request title"
    default: "feat: update translations via @LingoDotDev"
    required: false
  working-directory:
    description: "Working directory"
    default: "."
    required: false
  process-own-commits:
    description: "Process commits made by this action"
    default: false
    required: false
