name: Publish PHP SDK to Packagist

on:
  push:
    branches:
      - main
    paths:
      - 'php/sdk/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
          tools: composer:v2

      - name: Install dependencies for SDK
        working-directory: ./php/sdk
        run: composer install --prefer-dist

      - name: Run tests
        working-directory: ./php/sdk
        run: vendor/bin/phpunit tests/

      # Code style checks removed as requested by user
      # - name: Check code style
      #   working-directory: ./php/sdk
      #   run: composer cs

  publish:
    needs: test
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, intl
          coverage: none
          tools: composer:v2

      - name: Ensure valid version exists in SDK
        run: |
          # Check if version is empty or invalid
          VERSION=$(php -r '
            $composerJson = json_decode(file_get_contents("php/sdk/composer.json"), true);
            echo isset($composerJson["version"]) ? $composerJson["version"] : "";
          ')
          
          if [[ -z "$VERSION" || ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Setting initial version to 0.1.0"
            php -r '
              $composerJson = json_decode(file_get_contents("php/sdk/composer.json"), true);
              $composerJson["version"] = "0.1.0";
              file_put_contents("php/sdk/composer.json", json_encode($composerJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
            '
            VERSION="0.1.0"
          fi
          
          echo "Initial version: $VERSION"

      - name: Get current version
        id: current_version
        run: |
          VERSION=$(php -r '
            $composerJson = json_decode(file_get_contents("php/sdk/composer.json"), true);
            echo $composerJson["version"];
          ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Bump patch version
        id: bump_version
        run: |
          # Get current version
          CURRENT_VERSION=${{ steps.current_version.outputs.version }}
          
          # Use PHP to increment patch version
          NEW_VERSION=$(php -r '
            $version = "${{ steps.current_version.outputs.version }}";
            list($major, $minor, $patch) = explode(".", $version);
            $patch++;
            echo "$major.$minor.$patch";
          ')
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          
          # Update version in SDK composer.json
          php -r '
          $composerJson = json_decode(file_get_contents("php/sdk/composer.json"), true);
          $composerJson["version"] = "${{ steps.bump_version.outputs.new_version }}";
          file_put_contents("php/sdk/composer.json", json_encode($composerJson, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
          '

      - name: Install root composer dependencies
        run: |
          # Install composer dependencies from root composer.json
          # This will create a vendor directory with the PHP SDK symlinked
          composer install --no-dev --no-interaction --prefer-dist

      - name: Commit and push version bump
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: bump PHP SDK version to ${{ steps.bump_version.outputs.new_version }}"
          file_pattern: php/sdk/composer.json
          commit_user_name: "Lingo.dev"
          commit_user_email: "hi@lingo.dev"
          push_options: "--force"

      - name: Publish to Packagist
        run: |
          # Use our custom script for reliable Packagist publishing
          export PACKAGIST_USERNAME=lingodotdev
          export PACKAGIST_API_TOKEN=${{ secrets.PACKAGIST_API_TOKEN }}
          export PACKAGE_NAME=lingodotdev/sdk
          php scripts/packagist-publish.php
